// Single source of truth — seeded from ES World's real course catalogue.
// (Dubai + London campuses. Extracted from uploaded course materials.)

export type Campus = "Dubai" | "London" | "Online";
export type Category =
  | "English"
  | "Spanish"
  | "Teacher Training"
  | "Higher Education"
  | "Professional"
  | "Careers";

export type Product = {
  id: string;
  name: string;
  campus: Campus;
  category: Category;
  stage: "Flagship" | "Growth" | "Established" | "New" | "Promo";
  oneLiner: string;
  audience: string;
  levels?: string;
  format: string;
  price: string;
  priceNote?: string;
  focus?: string[];
  tags: string[];
  health: number; // programme health 0-100
  assets: number; // marketing/knowledge assets on file
  internal?: boolean;
  updated: string;

  // ---- Rich PM detail (all optional) ----
  overview?: string;
  prerequisites?: string;
  outcomes?: string[];
  outline?: string[]; // modules / topics
  schedule?: string; // timetables
  materials?: string;
  assessment?: string; // assessment & certification
  accreditation?: string;
  intakes?: string; // start dates
  enrolment?: string[]; // enrolment steps
  whyChoose?: string[];
  capacity?: string;
  owner?: string;
  documents?: { name: string; type: string; url?: string }[];
  positioning?: string;
  personas?: { who: string; need: string }[];
};

export const BRAND = {
  name: "ES World",
  motif: "Experience · Grow · Enjoy",
  site: "esworld.com",
  proof: [
    "106+ nationalities",
    "Student support in 20+ languages",
    "Dedicated careers office",
    "Cambridge CELTA centre",
    "Official IELTS test centre",
    "British Council accredited (UK)",
  ],
};

export const PRODUCTS: Product[] = [
  {
    id: "athe-diploma",
    name: "Business & Management Diploma",
    campus: "Dubai",
    category: "Higher Education",
    stage: "Flagship",
    oneLiner:
      "ATHE Level 4 & 5 Extended Diploma with a university progression pathway (De Montfort).",
    audience: "International students (17+) seeking a UK-accredited business qualification + UAE study visa.",
    levels: "ATHE Level 4 & 5",
    format: "1-year programme · September 2026 intake",
    price: "$17,000",
    priceNote: "Bundles tuition + Career Accelerator + AI Module + ATHE registration. Up to $3,000 discounts.",
    focus: ["Business & Management", "University progression", "Study visa", "Career Accelerator", "AI Module"],
    tags: ["diploma", "study-abroad", "visa", "flagship", "DMU pathway"],
    health: 86,
    assets: 6,
    updated: "Apr 2026",
    overview:
      "A one-year, UK-accredited business qualification in Dubai. Combines the ATHE Level 4 & 5 Extended Diploma with a structured Career Accelerator internship and an AI Module, on a UAE study visa — with a guaranteed progression route to a UK university (De Montfort).",
    prerequisites: "17+; secondary school completion; English at IELTS 5.5+ or internal assessment.",
    outcomes: [
      "A UK-recognised Level 4 & 5 business qualification",
      "Direct progression to a UK bachelor's (top-up year)",
      "Real UAE work experience via the Career Accelerator",
      "Practical AI-for-business skills",
    ],
    outline: [
      "Level 4 — business environment, people & communication, finance, marketing",
      "Level 5 — strategy, management, research project",
      "Career Accelerator — internship placement (LOI, host match, offer)",
      "AI Module",
    ],
    accreditation: "ATHE (UK, Ofqual-regulated). University progression: De Montfort University (letters of recognition & progression on file).",
    intakes: "September 2026 (main intake).",
    enrolment: ["Enquiry & eligibility check", "Application + documents", "Offer + visa processing", "Enrolment & induction"],
    whyChoose: ["UK qualification without leaving Dubai", "Internship + AI module bundled", "Guaranteed university progression", "Up to $3,000 scholarships"],
    owner: "Ryan (Academic) · Ivana/Josef (Admissions)",
    positioning: "The only route in Dubai to a UK-accredited business qualification with a guaranteed university progression path — bundled with real work experience and AI skills.",
    personas: [
      { who: "Ambitious school-leaver", need: "A globally recognised qualification and a clear path to a UK degree, without leaving the region." },
      { who: "Career-switcher", need: "A fast, credible business credential plus hands-on UAE work experience." },
      { who: "Parent / sponsor", need: "Value for money, real accreditation, and a safe, supported study-abroad experience." },
    ],
    documents: [
      { name: "ATHE Level 4 & 5 Extended Diploma Brochure", type: "Brochure" },
      { name: "ATHE Diploma Presentation", type: "Deck" },
      { name: "ATHE Price List (Apr 2026)", type: "Price list" },
      { name: "ATHE Level 5 Combined Specification v2.0", type: "Spec" },
      { name: "DMU Letter of Recognition", type: "Letter" },
      { name: "DMU Progression Letter", type: "Letter" },
      { name: "Sample Certificate — ATHE Level 5", type: "Sample" },
    ],
  },
  {
    id: "uae-pathways",
    name: "University Pathways (UAE Partners)",
    campus: "Dubai",
    category: "Higher Education",
    stage: "Growth",
    oneLiner: "Guaranteed scholarships and expert placement into top international universities in the UAE.",
    audience: "Students seeking UG/PG degrees in Dubai with scholarship support and visa continuity.",
    levels: "Undergraduate & Postgraduate",
    format: "Placement service · January & September intakes · 100% free application support",
    price: "From $11K/yr (UG) · 10–40% scholarships",
    priceNote:
      "8 partner universities (Wollongong, Heriot-Watt, Middlesex, RIT, Murdoch, SAE, Canadian University Dubai, Emirates Academy). UG $11K–$45K, PG $16K–$29K per year.",
    focus: ["University placement", "Scholarships", "Application support", "Visa continuity", "Transfer abroad"],
    tags: ["pathways", "university", "scholarships", "higher-ed", "placement"],
    health: 80,
    assets: 3,
    updated: "2026",
    overview:
      "Free placement service into top international universities in the UAE, with guaranteed scholarships and full application support. Study in Dubai for an internationally recognised degree, with the option to transfer abroad.",
    outline: [
      "University of Wollongong Dubai",
      "Heriot-Watt University Dubai",
      "Middlesex University Dubai",
      "Rochester Institute of Technology (RIT) Dubai",
      "Murdoch University Dubai",
      "SAE Institute Dubai",
      "Canadian University Dubai",
      "Emirates Academy of Hospitality",
    ],
    intakes: "January & September.",
    enrolment: ["Free consultation & shortlist", "Application to partner university", "Scholarship & offer", "Visa & enrolment"],
    whyChoose: ["Guaranteed scholarships (10–40%)", "100% free application support", "Stay in Dubai, degree recognised globally", "Transfer-abroad option"],
    owner: "Admissions (Ivana/Josef)",
    positioning: "A free, guaranteed-scholarship gateway into top UAE universities — study in Dubai, get a globally recognised degree, and transfer abroad if you choose.",
    personas: [
      { who: "Value-seeking undergraduate", need: "A recognised degree in Dubai with the biggest possible scholarship." },
      { who: "Postgraduate", need: "A flexible PG option with visa continuity and UAE career prospects." },
    ],
    documents: [
      { name: "University Pathways — Application Form", type: "Form", url: "https://esworld.jotform.com/242453955321961" },
      { name: "ES Pathway Guaranteed Scholarships (Students)", type: "Flyer" },
      { name: "ES Pathway Guaranteed Scholarships (Agents)", type: "Flyer" },
      { name: "University Applications Process", type: "Guide" },
    ],
  },
  {
    id: "dxb-tailored",
    name: "Tailor-Made General English (1-1)",
    campus: "Dubai",
    category: "English",
    stage: "Growth",
    oneLiner: "Fully personalised one-to-one English, built around each learner's goals.",
    audience: "Professionals & residents needing flexible, goal-specific English.",
    levels: "A1–C2",
    format: "45-min private lessons · flexible scheduling",
    price: "AED 200–250 / lesson",
    priceNote: "AED 250 (1–9 lessons) · AED 200 (10+ lessons).",
    focus: ["IELTS", "Academic Writing", "Business English", "Public Speaking", "Interview Skills", "Fluency"],
    tags: ["1-1", "general-english", "flexible"],
    health: 82,
    assets: 3,
    updated: "2026",
    overview:
      "Fully personalised one-to-one English, built entirely around the learner's goals — IELTS, interview prep, business communication, academic writing or fluency. 45-minute lessons with a dedicated teacher and flexible scheduling.",
    prerequisites: "Any level (A1–C2); an initial evaluation sets the starting point.",
    outcomes: ["Faster progress on a specific goal (exam, work, fluency)", "A tailored syllabus and a dedicated teacher"],
    schedule: "45-minute lessons scheduled around the learner (daytime or evening).",
    materials: "Bespoke materials selected to the goal; course book optional (extra).",
    whyChoose: ["100% tailored to your goal", "Dedicated teacher", "Flexible timing", "Fast results"],
    enrolment: ["Initial evaluation", "Agree goals & schedule", "Book lessons (AED 250 first 9 · AED 200 from the 10th)", "Start"],
    owner: "Nicky/Majid (Academic, Dubai)",
    documents: [{ name: "Dubai Tailor-Made General English Course 2026", type: "Course PDF" }],
  },
  {
    id: "dxb-speaking",
    name: "Speaking Class (English for All)",
    campus: "Dubai",
    category: "English",
    stage: "Promo",
    oneLiner: "Small-group daytime speaking course for real conversational confidence.",
    audience: "A2–C1 learners wanting to speak, not just study.",
    levels: "Lower A2/B1 · Mid B1–B1+ · Higher B2–C1",
    format: "3 days/week daytime · 9 lessons · min 4 weeks",
    price: "AED 320–430 / week",
    priceNote: "430 (4–8w) · 350 (9–16w) · 320 (17w+). Promo to 31 Jul 2026, UAE residents.",
    focus: ["Speaking", "Fluency", "Confidence"],
    tags: ["group", "speaking", "promo", "daytime"],
    health: 78,
    assets: 2,
    updated: "Jul 2026",
    overview: "A small-group daytime speaking course focused purely on conversational confidence — three days a week, real-world topics, structured by level.",
    schedule: "3 days/week, daytime · 9 lessons · minimum 4 weeks.",
    outcomes: ["Speak with more confidence", "Better fluency and pronunciation"],
    enrolment: ["Level check", "Choose weeks (promo pricing)", "Enrol (UAE residents, Emirates ID)", "Start"],
    owner: "Nicky/Majid (Academic, Dubai)",
    documents: [{ name: "Dubai Speaking Class Promotion 2026", type: "Flyer" }],
  },
  {
    id: "dxb-general",
    name: "General English (Group)",
    campus: "Dubai",
    category: "English",
    stage: "Growth",
    oneLiner: "Group General English building all four skills — intensive & semi-intensive options.",
    audience: "Learners wanting structured group English across speaking, listening, reading & writing.",
    levels: "A1–C2",
    format: "Group classes · intensive & semi-intensive · JLT & JBR campuses",
    price: "From USD 225 / week",
    priceNote: "Semi-intensive (15 lessons/wk): USD 340→225/wk by length. Intensive (30/wk): USD 550→385/wk. VAT-incl. Local AED rates also available.",
    focus: ["Speaking", "Listening", "Reading", "Writing", "Grammar"],
    tags: ["general-english", "group", "intensive", "website"],
    health: 79,
    assets: 1,
    updated: "2026 (site)",
    overview: "Structured group English across all four skills — speaking, listening, reading and writing — at semi-intensive (15 lessons/wk) or intensive (30 lessons/wk) pace.",
    outcomes: ["Steady progress through the CEFR levels", "Stronger everyday and academic English"],
    outline: ["Speaking & listening", "Reading & writing", "Grammar & vocabulary", "Regular progress tests"],
    owner: "Nicky/Majid (Academic, Dubai)",
  },
  {
    id: "dxb-business",
    name: "Business English",
    campus: "Dubai",
    category: "English",
    stage: "Growth",
    oneLiner: "Professional English for the workplace — meetings, presentations, email and negotiation.",
    audience: "Working professionals and teams operating in English.",
    levels: "B1–C1",
    format: "Group / private options · Dubai campus",
    price: "From USD 225 / week",
    priceNote: "English for Business (max 12 wks). Semi-intensive USD 340→225/wk · intensive USD 550→385/wk. VAT-incl.",
    focus: ["Meetings", "Presentations", "Negotiation", "Business writing"],
    tags: ["business-english", "professional", "website"],
    health: 73,
    assets: 1,
    updated: "2026 (site)",
    overview: "Professional English for the workplace — meetings, presentations, negotiation and business writing — available group or private.",
    outcomes: ["Communicate confidently at work", "Sharper meetings, emails and presentations"],
    outline: ["Meetings & discussion", "Presentations", "Negotiation", "Business writing & email"],
    owner: "Nicky/Majid (Academic, Dubai)",
  },
  {
    id: "dxb-ielts",
    name: "IELTS Preparation",
    campus: "Dubai",
    category: "English",
    stage: "New",
    oneLiner: "Focused IELTS preparation to reach your target band — Pre-Intermediate & Intermediate entry.",
    audience: "Students & professionals needing IELTS for university, migration, or work.",
    levels: "Pre-Intermediate (B1) · Intermediate (B1+–B2)",
    format: "Group preparation course · Dubai campus",
    price: "From USD 225 / week",
    priceNote: "IELTS Preparation (max 6 wks semi-intensive). USD 340→225/wk semi · 550→385/wk intensive. VAT-incl. ES is an official IELTS test centre.",
    focus: ["Listening", "Reading", "Writing", "Speaking", "Exam strategy", "Band targeting"],
    tags: ["ielts", "exam-prep", "group", "new-launch"],
    health: 66,
    assets: 4,
    updated: "2026",
    overview: "Focused IELTS preparation across all four papers, with exam strategy and band targeting. ES is an official IELTS test centre.",
    outcomes: ["Hit your target IELTS band", "Confident exam technique across all four skills"],
    outline: ["Listening", "Reading", "Writing (Task 1 & 2)", "Speaking", "Exam strategy & mock tests"],
    owner: "Nicky/Majid (Academic, Dubai)",
  },
  {
    id: "dxb-flex",
    name: "Flex Evening Lessons",
    campus: "Dubai",
    category: "English",
    stage: "New",
    oneLiner: "Membership-based, standalone evening speaking sessions — attend at your own pace.",
    audience: "Working professionals who want real-world English around a busy schedule.",
    levels: "A2/B1 (guided) · B2/C1 (discussion-led)",
    format: "Weekday evenings 6:30–8pm · JLT campus · 15–20 per session",
    price: "Membership",
    priceNote: "First session free. Not eligible for credit/weeks transfer or visa sponsorship.",
    focus: ["Presentations", "Debate", "Negotiation", "Storytelling", "Workplace communication"],
    tags: ["membership", "evening", "flexible", "jlt"],
    health: 64,
    assets: 4,
    updated: "2026",
    overview: "Membership-based, standalone evening speaking sessions at the JLT campus — attend at your own pace around a busy schedule. First session free.",
    outcomes: ["Real-world speaking confidence", "Practice presentations, debate and negotiation"],
    outline: ["Presentations", "Debate", "Negotiation", "Storytelling", "Workplace communication"],
    owner: "Nicky/Majid (Academic, Dubai)",
    documents: [{ name: "ES World Flex Lessons Flyer", type: "Flyer" }, { name: "Dubai Flex Lessons — Prices 2026", type: "Price list" }],
  },
  {
    id: "dxb-spanish",
    name: "Private Spanish Lessons",
    campus: "Dubai",
    category: "Spanish",
    stage: "Growth",
    oneLiner: "One-to-one Spanish with native-level tutors, tailored to your pace.",
    audience: "Residents & travellers learning Spanish.",
    levels: "A1–C1",
    format: "Private lessons · flexible scheduling",
    price: "On request",
    focus: ["Conversation", "Travel Spanish", "Grammar"],
    tags: ["spanish", "1-1", "languages"],
    health: 70,
    assets: 2,
    updated: "2026",
    overview: "One-to-one Spanish with native-level tutors, tailored to your pace — from complete beginner to conversational fluency.",
    outcomes: ["Speak Spanish with confidence", "A syllabus built around your goals"],
    outline: ["Conversation & pronunciation", "Grammar foundations", "Travel & everyday Spanish"],
    owner: "Academic (Dubai)",
    documents: [{ name: "ES World Private Spanish Classes Flyer", type: "Flyer" }],
  },
  {
    id: "dxb-dmi",
    name: "Digital Marketing Course (DMI)",
    campus: "Dubai",
    category: "Professional",
    stage: "New",
    oneLiner: "Globally recognised Digital Marketing certification, accredited by the Digital Marketing Institute.",
    audience: "Professionals & career-changers wanting an industry-recognised digital marketing credential.",
    levels: "Professional certification",
    format: "Blended · MyDMI platform + taught sessions · includes DMI exam voucher",
    price: "USD 1,860 + 555 reg",
    priceNote: "Course USD 1,860 (6 wks, semi-intensive) + USD 555 DMI registration. VAT-incl.",
    focus: ["SEO & SEM", "Social media", "Content & email", "Analytics", "Strategy", "DMI exam prep"],
    tags: ["dmi", "digital-marketing", "certification", "professional"],
    health: 67,
    assets: 6,
    updated: "2026",
    overview:
      "A globally recognised Digital Marketing certification, accredited by the Digital Marketing Institute (DMI). Blended delivery on the MyDMI platform plus taught sessions, including the official DMI exam voucher.",
    outline: ["SEO & SEM", "Social media marketing", "Content & email", "Analytics", "Digital strategy", "DMI exam preparation"],
    assessment: "Official DMI certification exam (voucher included).",
    intakes: "Rolling · 6-week semi-intensive.",
    documents: [
      { name: "ES Digital Marketing Course PPT", type: "Deck" },
      { name: "New Flyer — Digital Marketing 2026", type: "Flyer" },
      { name: "Detailed Course Outline (on request)", type: "Outline" },
      { name: "DMI Registration + Exam Voucher", type: "Guide" },
      { name: "Sample Certificate — DMI", type: "Sample" },
    ],
  },
  {
    id: "dxb-celta",
    name: "CELTA Teacher Training",
    campus: "Dubai",
    category: "Teacher Training",
    stage: "Established",
    oneLiner: "Cambridge CELTA — the world-recognised English teaching qualification.",
    audience: "Aspiring & current English teachers (C1+, 18+). No prior experience needed.",
    levels: "Requires English C1 (≈IELTS 7)",
    format: "Face-to-face full-time 4wk OR online part-time 10wk · 9 runs in 2026",
    price: "From USD 1,995",
    priceNote: "Online (10 wks) USD 1,995 · Face-to-face (4 wks) USD 2,495. VAT-incl.",
    focus: ["Teaching methodology", "Assessed teaching practice", "Cambridge certification"],
    tags: ["celta", "cambridge", "teacher-training", "certification"],
    health: 80,
    assets: 4,
    updated: "2026",
    overview:
      "The Cambridge CELTA — the world's most recognised initial qualification for teaching English. A 4-week full-time face-to-face course or a 10-week part-time online course, with assessed teaching practice throughout.",
    prerequisites: "18+; English at C1 (≈ IELTS 7); no prior teaching experience needed.",
    outline: ["Foundations of ELT", "Core teaching skills", "Advanced methods", "Assessed teaching practice & written assignments"],
    assessment: "Continuous assessment — assessed teaching practice plus written assignments, Cambridge-moderated.",
    intakes: "9 course runs across 2026.",
    owner: "Ryan (Academic Director)",
    documents: [
      { name: "ES CELTA Course Flyer 2026", type: "Flyer" },
      { name: "CELTA Institutional Presentation", type: "Deck (internal)" },
      { name: "New CELTA Course Flyer + Offer", type: "Flyer" },
    ],
  },
  {
    id: "dxb-careers",
    name: "Career Accelerator (Study & Work)",
    campus: "Dubai",
    category: "Careers",
    stage: "Growth",
    oneLiner: "English study paired with a structured internship placement in the UAE.",
    audience: "International students seeking UAE work experience.",
    format: "Study + guided internship (LOI, host match, offer)",
    price: "Bundled / on request",
    priceNote: "Included in the ATHE Diploma; also available standalone.",
    focus: ["Internship placement", "Employability", "Work experience"],
    tags: ["careers", "internship", "study-work"],
    health: 68,
    assets: 4,
    internal: true,
    updated: "2026",
    overview: "English study paired with a structured internship placement in the UAE — supported end to end (LOI, host match, provisional offer). Included in the ATHE Diploma or available standalone.",
    outcomes: ["Real UAE work experience", "A stronger CV and employability", "A guided path from study to work"],
    outline: ["English study", "Employability prep", "Host matching (LOI)", "Internship placement & offer"],
    owner: "Careers office · Ivana/Josef (Admissions)",
    documents: [
      { name: "LOI — Intern Package Outline (sample)", type: "Sample" },
      { name: "Provisional Offer of Employment (sample)", type: "Sample" },
      { name: "Host Sample", type: "Sample" },
      { name: "Careers Study & Work PPT", type: "Deck" },
    ],
  },
  {
    id: "ldn-tailored",
    name: "Tailor-Made General English (1-1)",
    campus: "London",
    category: "English",
    stage: "Growth",
    oneLiner: "London one-to-one English tailored to each learner's goals.",
    audience: "Professionals & visitors studying English in London.",
    levels: "A1–C2",
    format: "Private lessons · flexible scheduling",
    price: "On request",
    focus: ["IELTS", "Business English", "Conversation"],
    tags: ["1-1", "london", "general-english"],
    health: 75,
    assets: 2,
    updated: "2026",
    overview: "London one-to-one English tailored to each learner's goals — IELTS, business or conversation — with native UK teachers.",
    outcomes: ["Fast progress on your specific goal", "A dedicated UK teacher"],
    outline: ["Tailored syllabus", "Speaking & fluency", "Exam or business focus"],
    owner: "Ben/Tagird (Academic, London)",
  },
  {
    id: "ldn-business",
    name: "Business English Course",
    campus: "London",
    category: "English",
    stage: "Growth",
    oneLiner: "Executive Business English for professionals working in English.",
    audience: "Working professionals & teams needing sharper business communication.",
    levels: "B1–C1",
    format: "Structured course · London campus",
    price: "From GBP 245 / week",
    priceNote: "English for Business (max 12 wks). Semi-intensive GBP 385→245/wk · intensive GBP 575→370/wk.",
    focus: ["Meetings", "Presentations", "Negotiation", "Email & reports"],
    tags: ["business-english", "london", "professional"],
    health: 74,
    assets: 3,
    updated: "2026",
    overview: "Executive Business English in central London for professionals working in English — meetings, presentations and negotiation.",
    outcomes: ["Confident business communication", "Sharper meetings & presentations"],
    outline: ["Meetings & discussion", "Presentations", "Negotiation", "Business writing"],
    owner: "Ben/Tagird (Academic, London)",
  },
  {
    id: "ldn-general",
    name: "General English (Group)",
    campus: "London",
    category: "English",
    stage: "Growth",
    oneLiner: "Group General English in central London with 100% native UK teachers.",
    audience: "International students studying English in London.",
    levels: "A1–C2",
    format: "Group classes · Bloomsbury (Russell Square) campus",
    price: "From GBP 245 / week",
    priceNote: "Semi-intensive (20 lessons/wk): GBP 385→245/wk. Intensive (40/wk): GBP 575→370/wk. British Council accredited.",
    focus: ["Speaking", "Listening", "Reading", "Writing", "British English"],
    tags: ["general-english", "group", "london", "website"],
    health: 76,
    assets: 1,
    updated: "2026 (site)",
    overview: "Group General English in central London (Bloomsbury) with 100% native UK teachers — semi-intensive (20 lessons/wk) or intensive (40 lessons/wk).",
    outcomes: ["Progress through the CEFR levels", "Authentic British English"],
    outline: ["Speaking & listening", "Reading & writing", "Grammar & vocabulary", "Progress tests"],
    owner: "Ben/Tagird (Academic, London)",
  },
  {
    id: "ldn-speaking",
    name: "English Speaking Class",
    campus: "London",
    category: "English",
    stage: "Growth",
    oneLiner: "Focused speaking course to build real conversational confidence in London.",
    audience: "Learners who want to speak fluently, not just study grammar.",
    levels: "A2–C1",
    format: "Group speaking sessions · London campus",
    price: "From GBP 245 / week",
    priceNote: "Group speaking. Semi-intensive GBP 385→245/wk · intensive GBP 575→370/wk.",
    focus: ["Speaking", "Fluency", "Pronunciation", "Confidence"],
    tags: ["speaking", "group", "london", "website"],
    health: 72,
    assets: 1,
    updated: "2026 (site)",
    overview: "A focused speaking course in London to build real conversational confidence, structured by level.",
    outcomes: ["Speak fluently and confidently", "Better pronunciation"],
    outline: ["Conversation", "Fluency & pronunciation", "Real-world topics"],
    owner: "Ben/Tagird (Academic, London)",
  },
  {
    id: "ldn-ielts",
    name: "IELTS Preparation",
    campus: "London",
    category: "English",
    stage: "Growth",
    oneLiner: "IELTS preparation in London to reach your target band.",
    audience: "Students & professionals needing IELTS for UK university, work, or migration.",
    levels: "B1–C1",
    format: "Group preparation course · London campus",
    price: "From GBP 245 / week",
    priceNote: "IELTS Prep (max 12 wks). Semi-intensive GBP 385→245/wk · intensive GBP 575→370/wk.",
    focus: ["Listening", "Reading", "Writing", "Speaking", "Exam strategy"],
    tags: ["ielts", "exam-prep", "london", "website"],
    health: 70,
    assets: 1,
    updated: "2026 (site)",
    overview: "IELTS preparation in London across all four papers, with exam strategy and band targeting.",
    outcomes: ["Hit your target IELTS band", "Confident exam technique"],
    outline: ["Listening", "Reading", "Writing", "Speaking", "Exam strategy"],
    owner: "Ben/Tagird (Academic, London)",
  },
  {
    id: "ldn-flex",
    name: "Flex Evening Lessons",
    campus: "London",
    category: "English",
    stage: "New",
    oneLiner: "Flexible evening group English around a working schedule.",
    audience: "London-based working professionals.",
    levels: "A2–C1",
    format: "Weekday evenings · flexible attendance",
    price: "Membership",
    tags: ["membership", "evening", "london"],
    health: 61,
    assets: 2,
    updated: "2026",
    overview: "Flexible evening group English in London, designed to fit around a working schedule.",
    outcomes: ["Real-world speaking practice", "Learn around work"],
    outline: ["Speaking & discussion", "Workplace English", "Real-world topics"],
    owner: "Niel (London Campus Director)",
  },
  {
    id: "ldn-celta",
    name: "Teacher Training (CELTA)",
    campus: "London",
    category: "Teacher Training",
    stage: "Established",
    oneLiner: "London-based Cambridge CELTA teacher training.",
    audience: "Aspiring & current English teachers (C1+).",
    format: "Full-time / part-time options",
    price: "On request",
    focus: ["Teaching methodology", "Assessed practice", "Cambridge certification"],
    overview: "London-based Cambridge CELTA teacher training — full-time or part-time — with assessed teaching practice throughout.",
    prerequisites: "18+; English at C1 (≈ IELTS 7); no prior teaching experience needed.",
    outline: ["Foundations of ELT", "Core teaching skills", "Advanced methods", "Assessed teaching practice"],
    assessment: "Continuous assessment — teaching practice plus written assignments, Cambridge-moderated.",
    owner: "Ben/Tagird (Academic, London)",
    tags: ["celta", "london", "teacher-training"],
    health: 77,
    assets: 3,
    updated: "2026",
  },
];

export const CATEGORIES: Category[] = [
  "Higher Education",
  "English",
  "Professional",
  "Spanish",
  "Teacher Training",
  "Careers",
];

export const PORTFOLIO_STATS = {
  programmes: PRODUCTS.length,
  campuses: 2,
  flagship: "$17K",
  atRisk: PRODUCTS.filter((p) => p.health < 65).length,
};
